version: 2
archives:
  - id: default
    allow_different_binary_count: true
builds:
  - env:
      - CGO_ENABLED=0
    id: tunnel
    binary: tunnel
    main: ./cmd/tunnel
    ldflags:
    - "-s -w -X 'github.com/coder/wgtunnel/buildinfo.tag={{.Version}}'"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - env:
      - CGO_ENABLED=0
    binary: tunneld
    main: ./cmd/tunneld
    id: tunneld
    ldflags:
    - "-s -w -X 'github.com/coder/wgtunnel/buildinfo.tag={{.Version}}'"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - "ghcr.io/tty0-it/wgtunnel/tunneld:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/tty0-it/wgtunnel/tunneld:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: "ghcr.io/tty0-it/wgtunnel/tunneld:{{ .Version }}"
    image_templates:
      - "ghcr.io/tty0-it/wgtunnel/tunneld:{{ .Version }}-amd64"
      - "ghcr.io/tty0-it/wgtunnel/tunneld:{{ .Version }}-arm64v8"